/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FeaturesGeneratorSchema {
  /**
   * The directory at which to create the files
   */
  directory: string
  /**
   * The prefix to use for the component
   */
  prefix?: string
  /**
   * The import path to the UI components
   */
  uiImport?: string
}
