/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ComponentGeneratorSchema {
  /**
   * The directory at which to create the files
   */
  directory: string
  /**
   * The type of component to create
   */
  type:
    | 'alert'
    | 'anchor'
    | 'avatar'
    | 'back'
    | 'card'
    | 'container'
    | 'copy'
    | 'dashboard-grid'
    | 'debug'
    | 'form'
    | 'grid-routes'
    | 'group'
    | 'header'
    | 'info-table'
    | 'helpers'
    | 'layout'
    | 'loader'
    | 'logo'
    | 'menu'
    | 'not-found'
    | 'page'
    | 'search-input'
    | 'select-enum'
    | 'stack'
    | 'tab-routes'
    | 'theme'
    | 'theme-select'
    | 'theme-switch'
    | 'time'
    | 'toast'
  /**
   * The prefix to use for the component
   */
  prefix?: string
}
