import { ComponentGeneratorSchema } from './component-generator-schema'

export const componentTypes: ComponentGeneratorSchema['type'][] = [
  'alert',
  'back',
  'card',
  'container',
  'copy',
  'dashboard-grid',
  'debug',
  'group',
  'header',
  'layout',
  'loader',
  'logo',
  'menu',
  'not-found',
  'search-input',
  'stack',
  'tab-routes',
  'theme',
  'theme-switch',
  'time',
  'toast',
]
